### ISSUE TITLE
After having aborted a print and opened the front door ..

### ISSUE THREAD

**Issue by homahe** [FABtotum/fabui-colibri#149]
You will have to reset the controller after having aborted a print and opened and closed the front cover, as it will not return from the 'emergency state'.

I'd guess it is a normal action to abort a print when you have to and open the cover to clean the print-bed and close the front cover thereafter. So either there should be a 'continue' button in this case after closing or the 'emergency state' cleared automatically.

**Comment by daniel-fabteam** [comment]
The issue should be fixed in the next update.

`Tip:` 
On abort gcode pushing is stopped and as totumduino has a buffer for the codes it has to execute them until the buffer is empty. 
Same applies to pause, totumduino must finish all buffered commands before it can stop.

On Emergenyc (button or door open) all operation as stopped immediately and totrumduino is reset so this should be used in case an immediate stop is desired.
