### ISSUE TITLE
Jog Panel

### ISSUE THREAD

**Issue by PaoloP74** [FABtotum/fabui-colibri#23]
When using the oblique arrows limit switches do not work.
The home button in the top jog panel does not work.

**Comment by daniel-fabteam** [comment]
Jog home button will be fixed in the next update.

Could you describe in more detail the issue with limit switches?
Is there not error message, or does the head hit the end without stopping?

Also check that your door is properly close so that the "Door Open Safety" is not reacting.
You can also disable the door safety in Settings -> Hardware.

**Comment by PaoloP74** [comment]
The head hit the end without stopping and without error message.
"Door Open Safety" was disable because I don't have reed sensor.
